install.packages("ggplot2")
install.packages("stringr")
install.packages("plyr")
install.packages("grid")
install.packages("gridExtra")
install.packages("methods")
install.packages("xtable")
install.packages("knitr")
